# Generated by Django 5.1.4 on 2025-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0023_alter_poster_quantity_alter_versionposter_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="label",
            field=models.CharField(default="", max_length=4096, verbose_name="Titel"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="label",
            field=models.CharField(default="", max_length=4096, verbose_name="Titel"),
        ),
    ]
