# Generated by Django 5.1.4 on 2025-06-23 12:21

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0032_remove_versionevent_version_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="end date"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="start date"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="end_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="end date"
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="end_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="end_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="end_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="start_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="start date"
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="start_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="start_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="start_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="end_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="end date"
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="end_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="end_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="end_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="start_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="start date"
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="start_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="start_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="start_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="end_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="end date"
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="end_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="end_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="end_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="start_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True, default="", verbose_name="start date"
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="start_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="start_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="start_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
    ]
