# Generated by Django 5.1.4 on 2025-06-18 10:01

"""
Data migration to move DB values of `Event` and `Performance` model classes'
`date_range` fields to new `start_date` and `end_date` fields.
These sets of new fields are meant to replace each current single field.
"""

from django.db import migrations
from functools import partial

import logging
import re

logger = logging.getLogger(__name__)

# list of dictionaries identifying which model fields need to have their
# values copied over to which other fields
UPDATE_FIELDS = [
    {
        "app": "apis_ontology",
        "models": ["Event", "VersionEvent", "Performance", "VersionPerformance"],
        "fields": {
            "source": {
                "name": "date_range",
                "value": None,
            },
            "target": [
                {
                    "name": "start_date",
                    "value": None,
                },
                {
                    "name": "end_date",
                    "value": None,
                },
            ],
        },
    },
]


def update_field_values(
    apps, schema_editor, from_key="source", to_key="target", reset=False
):
    """
    Copy existing field values in the database over to new fields for every
    match between `source` field and `target` fields.

    Assumes affected fields contain strings (CharField, TextField,...)
    or a list of strings (ArrayField with e.g. CharField for base_field).

    :param from_key: identifies the source field
    :type from_key: str
    :param to_key: identifies the target field(s)
    :type to_key: list
    """
    for item in UPDATE_FIELDS:
        for model_name in item["models"]:
            model_class = apps.get_model(item["app"], model_name)

            all_objects = model_class.objects.all()

            for inst in all_objects:
                from_field_name = item["fields"].get(from_key, {}).get("name")

                to_fields = item["fields"].get(to_key, [])
                instance_field_data = getattr(inst, from_field_name, None)

                if instance_field_data and to_fields:
                    update_fields = []

                    converted_data = convert_values(instance_field_data)

                    for index, x in enumerate(to_fields):
                        to_field_name = x.get("name")
                        value = converted_data[index]

                        if value:
                            update_fields.append(to_field_name)
                            logger.debug(
                                f"Set {model_name} field {to_field_name} to {value}."
                            )
                            setattr(inst, to_field_name, value)

                    if hasattr(inst, "skip_history_when_saving"):
                        inst.skip_history_when_saving = True

                    logger.debug(update_fields)
                    update_fields.reverse()

                    logger.debug(update_fields)
                    inst.save(update_fields=update_fields)


def convert_values(data):
    from_date = None
    to_date = None

    ab = re.search("ab ([0-9.-]*)", data)
    bis = re.search("bis ([0-9.-]*)", data)
    single_date = re.search("^[0-9.-]*$", data)

    if ab:
        from_date = ab.group(1)
    if bis:
        to_date = bis.group(1)
    if single_date:
        from_date = to_date = single_date.group()

    return from_date, to_date


def reset_new_fields(apps, schema_editor, to_key="target"):
    """Set values of new fields back to None."""
    for item in UPDATE_FIELDS:
        for model in item["models"]:
            model_class = apps.get_model(item["app"], model)

            all_objects = model_class.objects.all()

            for inst in all_objects:
                to_fields = item["fields"].get(to_key, [])

                if to_fields:
                    update_fields = []
                    # set all to_field values empty (if not already empty)
                    for field in to_fields:
                        field_name = field["name"]
                        field_data = getattr(inst, field_name, None)
                        if field_data:
                            setattr(inst, field_name, "")
                            # inst.save()
                            # update_fields += [
                            #     f"{field_name}_date_from",
                            #     f"{field_name}_date_to",
                            #     f"{field_name}_date_sort",
                            # ]
                            # for f in update_fields:
                            #     setattr(inst, f, "")
                            #
                            # update_fields.append(field_name)

                    logger.debug(update_fields)

                    inst.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0033_event_end_date_event_end_date_date_from_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=update_field_values,
            reverse_code=partial(
                reset_new_fields,
            ),
        ),
    ]
